### ISSUE TITLE
page margin issue

### ISSUE THREAD

**Issue by chenlabucd** [kogakure/ia-writer-template-shibui#1]
Thanks for sharing this beautiful theme.

When in viewing mode (both in web and pdf), there is no left margin. Exported pdf has the same issue

(https://user-images.githubusercontent.com/94983425/193431255-80e577af-8656-413a-8bef-dd77788d3362.png)

This happens on Mac OS with iA 6.0.4.

**Comment by kogakure** [comment]
Unfortunately, I cannot reproduce your issue. I don’t see it either in Web or PDF preview (macOS in 6.0.4). I had a look at the CSS, and it uses viewport units for different window widths and is automatically centered. Technically, it should not be possible to reach the edge at all.

https://github.com/kogakure/ia-writer-template-shibui/blob/f124f5c9f5c227ecfc849675a53639973e842c0b/Shibui.iatemplate/Contents/Resources/styles/style.css#L36-L57

If you have a few technical skills, you could try to inspect your CSS. You need to activate the debugging feature for iA Writer as described [here](https://github.com/iainc/iA-Writer-Templates#developing-templates) by pasting this to a terminal:

```sh
defaults write pro.writer.mac WebKitDeveloperExtras -bool true
```

Subsequently, you can click on the preview window with the right mouse and inspect the code to see why the margins are missing.

**Comment by kogakure** [comment]
I have an idea … Can you check what Safari you use? It might be that iA Writer is using Safari to render this view. I use a [CSS logical property](https://caniuse.com/mdn-css_properties_margin-inline), which is supported since Safari 14.1. If you have an earlier version, it might not work. If this is the case, I can probably fix it by supporting the older syntax.

**Comment by chenlabucd** [comment]
Thanks for your reply and attention.

I am not good with code. Safari was 14.1, and after it was updated to 15.6.1. and I restarted the Mac, but there is still no left margin. 

It's kinda weird. I downloaded both of your themes at the very same time. Everything works with your 南山 theme or with any other themes that come with iA writer itself.

**Comment by kogakure** [comment]
There is a difference between the two templates, but it’s not the usage of CSS logical properties. I found that in the other template I used `safe-area-inset` properties the example templated used. As it worked on my computer without those, I removed them in the second template. I’m not able to test it, because it already works, but I opened a pull request with a fix and will create a new version `1.0.1` after the merge. Please tell me if it worked.

**Comment by kogakure** [comment]
You can find the new release here, https://github.com/kogakure/ia-writer-template-shibui/releases/tag/1.0.1. Remove the old template first from the settings before installing the new one (to be sure, the new one is used).

**Comment by chenlabucd** [comment]
Thank you! 

Just tried the new version. The web is good now, but still not for PDF mode.

I can use 南山 instead. Don't worry about to find a "fix".

**Comment by kogakure** [comment]
Try this version, I had to fix another bug, and hope I fixed the PDF problem, too. https://github.com/kogakure/ia-writer-template-shibui/releases/tag/1.0.2

**Comment by chenlabucd** [comment]
This version 1.0.2  _**worked**!_

Looking so good. 
![screenshot](https://user-images.githubusercontent.com/94983425/193467294-2338b50f-3844-4643-8a5e-906d79397e63.png)

Thank you 💯
